# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 13:09
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'open'), (1, 'close')], default=0, verbose_name='status'),
        ),
    ]
