# Generated by Django 2.0.8 on 2018-11-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_emailsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='doc_in_link',
            field=models.BooleanField(default=False, verbose_name='documents in link'),
        ),
    ]
