# Generated by Django 2.1.8 on 2019-06-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_message_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='documents',
            field=models.ManyToManyField(blank=True, to='documents.DocumentContainer', verbose_name='documents'),
        ),
    ]
