# Generated by Django 3.2.16 on 2022-10-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_possession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='args',
            field=models.TextField(default='{}', verbose_name='arguments'),
        ),
    ]
