# Generated by Django 4.2 on 2025-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_customfield_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='legal_identification',
            field=models.CharField(blank=True, max_length=30, verbose_name='legal identification'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='vat_identification',
            field=models.CharField(blank=True, max_length=20, verbose_name='VAT identification number'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='identify_number',
            field=models.TextField(blank=True, verbose_name='other identify information'),
        ),
    ]
